# Generated by Django 6.1 on 2026-08-17 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.IntegerField()),
                ('release_date', models.DateField()),
                ('age_certification', models.CharField(max_length=100)),
                ('trailer_url', models.URLField(max_length=1000)),
                ('Language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.language')),
                ('genres', models.ManyToManyField(to='movies.genre')),
            ],
        ),
    ]
