# Generated by Django 6.1 on 2026-08-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_language_movie_language_castmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='castmember',
            name='movies',
        ),
        migrations.AddField(
            model_name='movie',
            name='cast_members',
            field=models.ManyToManyField(to='movies.castmember'),
        ),
    ]
