# Generated by Django 6.1 on 2026-08-18 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_theatre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_seats', models.IntegerField()),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.theatre')),
            ],
        ),
    ]
