# Generated by Django 6.1 on 2026-08-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castmember',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
