# Generated by Django 6.1 on 2026-08-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='reserved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
